version: '3.8'

services:
  imx6:
    init: true
    build:
      context: ../
      dockerfile: imx6/Dockerfile
    image: imx6:V1.0.9
    hostname: imx6
    container_name: imx6
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    ports:
      - "18899:22"
    volumes:
      - /srv/tftp/:/srv/tftp
      - /mnt/hgfs/share:/mnt/hgfs/share
      - ~/.local/bin:/root/.local/bin:ro
      - /workspace/imx6ull:/workspace/imx6ull
      - /workspace/note:/workspace/note
      - ~/.local/share/todo:/root/.local/share/todo
    restart: unless-stopped
